spring.mvc.locale-resolver=fixed
spring.mvc.locale="pt_BR"


spring.application.name=backend-java
spring.jpa.hibernate.ddl-auto= none

spring.datasource.url = jdbc:postgresql://localhost:5432/db_approval
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
#spring.datasource.password=masterkey
spring.datasource.driver-class-name = org.postgresql.Driver


spring.jpa.generate-ddl = true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#define a porta do servidor
server.port = 3333
#define  a base padrao para todos os endpoit da api
server.servlet.context-path=/api/v1


#define que o progrma esta no modo dev
spring.profiles.active=dev

#cria urls para monitar a aplicacao
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always